select * from customers
select * from geolocation
select * from order_items
select * from order_payments
select * from order_reviews
select * from products
select * from sellers


--1. What is the total revenue generated by Olist AND PAYEMNT_TYPE, and how has it changed over time?
SELECT
	p.payment_type,
	ROUND(SUM(p.payment_value),2) as Total_Revenue
FROM order_payments p INNER JOIN orders o
ON p.order_id = o.order_id
GROUP BY p.payment_type
ORDER BY ROUND(SUM(p.payment_value),2) DESC
-- Monthly revenue by year and month
SELECT 
	FORMAT(o.order_purchase_timestamp,'yyyy_MMM') AS DATE ,
	ROUND(SUM(p.payment_value),2) as Total_Revenue
FROM  order_payments p INNER JOIN orders o
ON p.order_id = o.order_id
GROUP BY FORMAT(o.order_purchase_timestamp,'yyyy_MMM')
ORDER BY FORMAT(o.order_purchase_timestamp,'yyyy_MMM')
--------------------------------------------------------------------------
--2. How many orders were placed on Olist, and how does this vary by month or season?
-- Monthly number of orders
SELECT 
	order_status,
	FORMAT(order_purchase_timestamp,'yyyy_MMM') AS DATE,
	COUNT(order_id) AS orders
FROM orders
GROUP BY order_status, FORMAT(order_purchase_timestamp,'yyyy_MMM')
ORDER BY order_status
-- seasonality number of orders
SELECT 
	order_status,
	YEAR(order_purchase_timestamp) AS YEAR,
	DATEPART(QUARTER,order_purchase_timestamp) AS QUARTER,
	COUNT(order_id) AS ORDERS
FROM orders
GROUP BY order_status, YEAR(order_purchase_timestamp),DATEPART(QUARTER,order_purchase_timestamp)
ORDER BY order_status
--------------------------------------------------------------------------------------------
--3. What are the most popular product categories on Olist, and how do their sales volumes compare to each other?
SELECT 
	C.product_category_name_english,
	ROUND(SUM(D.payment_value),2) AS total_revenue
FROM order_items O
INNER JOIN order_payments D ON O.order_id = D.order_id
INNER JOIN products P ON o.product_id = p.product_id
INNER JOIN product_category_name_translation C ON p.product_category_name = C.product_category_name
GROUP BY  product_category_name_english
ORDER BY  COUNT(O.order_id) DESC
--------------------------------------------------------------------------------------------
--4. What is the average order value (AOV) on Olist, and how does this vary by product category or payment method?
--By Product Category
SELECT 
	pt.product_category_name_english ,
	ROUND(SUM(payment_value),2) /COUNT(op.order_id) AS AOV_by_Category
FROM products p 
INNER JOIN product_category_name_translation pt ON p.product_category_name = pt.product_category_name
INNER JOIN order_items ot ON ot.product_id = p.product_id
INNER JOIN order_payments op ON op.order_id=ot.order_id
GROUP BY pt.product_category_name_english 
ORDER BY ROUND(SUM(payment_value),2) /COUNT(op.order_id) DESC
--By Payment Method
SELECT 
	op.payment_type ,
	ROUND(SUM(payment_value),2) /COUNT(op.order_id) AS AOV_by_Category
FROM products p 
INNER JOIN order_items ot ON ot.product_id = p.product_id
INNER JOIN order_payments op ON op.order_id=ot.order_id
GROUP BY op.payment_type
ORDER BY ROUND(SUM(payment_value),2) /COUNT(op.order_id) DESC
--5. How many sellers are active on Olist, and how does this number change over time?
--seller is active is if they were able to successfully deliver an item to the customer 
--and the order should have been made within the last 30 days from the most recent order purchase date.
WITH Active_Saller AS (
SELECT 
	s.seller_id,
	MIN(o.order_purchase_timestamp) AS first_order,
    MAX(o.order_purchase_timestamp) AS last_order,
	DATEDIFF (DAY,MIN(o.order_purchase_timestamp) , MAX(o.order_purchase_timestamp)) AS ActiveOrders
FROM order_items oi
INNER JOIN orders o ON oi.order_id = o.order_id 
INNER JOIN sellers s ON oi.seller_id = s.seller_id
group by s.seller_id
HAVING DATEDIFF (DAY,MIN(o.order_purchase_timestamp) , MAX(o.order_purchase_timestamp)) <= 60
)
Select COUNT(DISTINCT seller_id) 
FROM Active_Saller

--------------------------------------------------------------------------------------------
--6. How many customers have made repeat purchases on Olist?
WITH Customers_repeat AS(
SELECT
	 c.customer_unique_id,
	 count(o.order_id) AS order_count
FROM  customers c INNER JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
HAVING  count(o.order_id) >1
)
SELECT
	COUNT(*)
FROM Customers_repeat

--------------------------------------------------------------------------------------------
--7. What is the average customer rating for products sold on Olist, and how does this impact sales performance?
WITH customer_rating AS (
SELECT 
	pt.product_category_name_english,
	o.order_status,
	o.order_approved_at,
	AVG(r.review_score) AS AVERAGE_SCORE,
	SUM(op.payment_value) AS TOTAL_REVENUE,
	AVG(op.payment_value) AS AVERGAE_REVENUE
FROM order_reviews r
INNER JOIN orders o ON r.order_id = o.order_id
INNER JOIN order_payments op ON op.order_id = r.order_id 
INNER JOIN order_items oi ON oi.order_id = op.order_id
INNER JOIN products p ON oi.product_id = p.product_id
INNER JOIN product_category_name_translation pt on p.product_category_name = pt.product_category_name
WHERE o.order_status!='canceled' AND o.order_approved_at IS NOT NULL
GROUP BY pt.product_category_name_english,o.order_status,o.order_approved_at
)
SELECT 
	*
FROM customer_rating
ORDER BY AVERAGE_SCORE DESC

--------------------------------------------------------------------------------------------
--8. What is the average order cancellation rate on Olist?
SELECT 
    CAST(COUNT(order_id) AS FLOAT) * 100 / 
    (SELECT COUNT(order_id) FROM orders) AS cancellation_rate_percent
FROM orders
WHERE order_status = 'canceled';
--------------------------------------------------------------------------------------------
--9. What are the top-selling products on Olist?
SELECT 
	P.product_id,
	PT.product_category_name_english, 
	COUNT(*) AS total_sold
FROM order_items OI
JOIN products P ON OI.product_id = P.product_id
JOIN product_category_name_translation PT ON P.product_category_name = PT.product_category_name
GROUP BY P.product_id, PT.product_category_name_english
ORDER BY total_sold DESC;
--------------------------------------------------------------------------------------------
--10. Which payment methods are most commonly used by Olist customers, and how does this vary by product category or geographic region?
SELECT
	payment_type,
	COUNT(payment_type) AS MOST_USED
FROM order_payments
GROUP BY payment_type
ORDER BY COUNT(payment_type) DESC
--by geographic region
SELECT 
	c.customer_state,
	op.payment_type,
	count(*)
FROM order_payments op
INNER JOIN orders o ON o.order_id = op.order_id
INNER JOIN customers c ON c.customer_id = o.customer_id
GROUP BY customer_state,op.payment_type
--------------------------------------------------------------------------------------------
--11. Which product categories have the highest profit margins on Olist?
SELECT 
	PT.product_category_name_english,
	(SUM(OP.payment_value) - SUM(OI.price) + SUM(OI.freight_value)) / SUM(OP.payment_value) * 100 AS profit_margin
FROM order_payments OP
JOIN order_items OI ON OP.order_id = OI.order_id
JOIN products P ON P.product_id = OI.product_id
JOIN product_category_name_translation PT ON PT.product_category_name = P.product_category_name
GROUP BY product_category_name_english
ORDER BY profit_margin DESC